
GET https://644fd9a0ba9f39c6ab6e09a7.mockapi.io/travelplan

###

PATCH https://644fd9a0ba9f39c6ab6e09a7.mockapi.io/travelplan/22
Content-Type: application/json

{
    "location": "Srinagar",
    "image": "https://th.readme.me/f/18619/cover.jpg",
    "plan": "16",
    "country": "India",
    "price":69000,
    "description": "Ladakh, 'the Land of High Passes', is a beautiful region in India. Snowcapped peaks, clear blue skies, barren mountains with meandering rivers, Ladakh is picturesque!"
} 


# const cartDiv = document.getElementById('product-page');
# const cart = document.getElementById('cart');

# cartDiv.addEventListener('scroll', function() {
#   if (cartDiv.scrollTop === 0) {
#     cartDiv.classList.add('fixed');
#     cart.classList.remove('fixed');
#   } else {
#     cartDiv.classList.remove('fixed');
#     cart.classList.add('fixed');
#   }
# });

# cart.addEventListener('scroll', function() {
#   if (cart.scrollTop === 0) {
#     cart.classList.add('scrollable');
#     cartDiv.classList.remove('fixed');
#     cart.classList.remove('fixed');
#   } else {
#     cart.classList.remove('scrollable');
#     cartDiv.classList.add('fixed');
#     cart.classList.add('fixed');
#   }
# });
